// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230530081906_initialmigration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2421a6c5-82c2-4210-9d31-c11889003e34"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 3, 30, 8, 19, 6, 499, DateTimeKind.Utc).AddTicks(1633),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("92002baa-699a-4932-b375-0535d1b5f3b9"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2023, 4, 30, 8, 19, 6, 499, DateTimeKind.Utc).AddTicks(1647),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("72825e06-69a9-4a31-985e-74971b6db9d7"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2023, 6, 30, 8, 19, 6, 499, DateTimeKind.Utc).AddTicks(1652),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("13c0a300-64df-4def-8606-986f23fdaec5"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 7, 30, 8, 19, 6, 499, DateTimeKind.Utc).AddTicks(1657),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("d835c310-83da-43c0-8d84-c67d5b48be6a"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 8, 30, 8, 19, 6, 499, DateTimeKind.Utc).AddTicks(1662),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("7257564f-aca3-49a0-bad1-cf8534884f63"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 9, 30, 8, 19, 6, 499, DateTimeKind.Utc).AddTicks(1666),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("b46186d1-194c-462f-a6af-2b28070434bc"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 10, 30, 8, 19, 6, 499, DateTimeKind.Utc).AddTicks(1671),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("f57b8853-9f39-4580-85cb-11bcb6995a32"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 11, 30, 8, 19, 6, 499, DateTimeKind.Utc).AddTicks(1676),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("c5c0defe-7938-4ae5-bbc1-5cd9cf5d6fc8"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2023, 12, 30, 8, 19, 6, 499, DateTimeKind.Utc).AddTicks(1680),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("25e07f83-07b1-4de8-b13d-dca3eca42ebd"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2024, 1, 30, 8, 19, 6, 499, DateTimeKind.Utc).AddTicks(1684),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
